# Generated by Django 5.1.1 on 2024-10-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_name', models.CharField(max_length=64)),
                ('spot_description', models.CharField(max_length=256)),
                ('spot_latitude', models.FloatField(default=0)),
                ('spot_longitude', models.FloatField(default=0)),
                ('photo', models.ImageField(upload_to='site_media')),
            ],
        ),
    ]
